---
name: jsonnet
permissions: {}
on:
  pull_request:
    branches: [main]
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - uses: aquaproj/aqua-installer@7c7338067bdb97d5bea2acc82b5870afca470d18 # v2.3.0
        with:
          aqua_version: v2.23.1
      - run: jsonnet --version
      - run: |
          bash scripts/generate.sh
          git add .
          if ! git diff --cached --exit-code; then
            echo "Please run 'bash scripts/generate.sh'" >&2
            echo "::error title=Please run 'bash scripts/generate.sh'::"
            exit 1
          fi
