---
name: jsonnet
permissions: {}
on:
  pull_request:
    branches: [main]
jobs:
  default:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.37.2
      - run: jsonnet --version
      - run: |
          bash scripts/generate.sh
          git add .
          if ! git diff --cached --exit-code; then
            echo "Please run 'bash scripts/generate.sh'" >&2
            echo "::error title=Please run 'bash scripts/generate.sh'::"
            exit 1
          fi
