name: renovate-config-validator

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/renovate-config-validator.yaml
      - renovate.json5
permissions: {}
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@b54483862375f51910a60c4f498e927d4f3df466 # v1.0.1
