---
name: jsonnet
permissions: {}
on: workflow_call
jobs:
  jsonnet:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
        with:
          aqua_version: v2.43.3
      - run: jsonnet --version
      - run: |
          bash scripts/generate.sh
          git add .
          if ! git diff --cached --exit-code; then
            echo "Please run 'bash scripts/generate.sh'" >&2
            echo "::error title=Please run 'bash scripts/generate.sh'::"
            exit 1
          fi
