name: Validate renovate config
on: workflow_call
jobs:
  validate:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          persist-credentials: false
      - run: |
          set -euo pipefail
          files=""
          while read -r file; do
            files="$files $file"
          done < <(git ls-files | grep -E "^[^/]+\.json$")
          npx --package renovate -c "renovate-config-validator --strict $files"
