name: Validate renovate config
on: workflow_call
jobs:
  validate:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # v3.1.0
        with:
          aqua_version: v2.40.0
      - run: ci-info run | sed "s/^export //" >> "$GITHUB_ENV"
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: |
          grep -E "^[^/]+\.json$" "$CI_INFO_TEMP_DIR/pr_all_filenames.txt" | while read -r file; do
            if [ -f "$file" ]; then
              npx --package renovate -c renovate-config-validator "$file"
            fi
          done
